=== JimenaVazquez/sew/xml/etapa.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.uniovi.es" xmlns="http://www.uniovi.es" elementFormDefault="qualified">

	<xs:element name="etapas">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="21" ref="etapa"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="etapa">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="número" />
				<xs:element ref="fecha" />
				<xs:element ref="salida" />
				<xs:element ref="meta" />
				<xs:element ref="tipo" />
				<xs:element ref="referencias" />
				<xs:element ref="media" />
				<xs:element ref="hitos" />
				<xs:element ref="puntos" />
				<xs:element ref="clasificaciones" />
			</xs:sequence>
			<xs:attribute name="longitud" use="required" >
				<xs:simpleType>
					<xs:restriction base="xs:float">
						<xs:minInclusive value="9.4" />
						<xs:maxInclusive value="210.8" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="tiempoGanador" use="required" >
				<xs:simpleType>
					<xs:restriction base="xs:duration">
						<xs:minInclusive value="PT0H0M0S" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="velocidadMediaGanador" use="required" >
				<xs:simpleType>
					<xs:restriction base="xs:nonNegativeInteger">
						<xs:minInclusive value="0" />
						<xs:maxInclusive value="120" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="desnivel" use="required" >
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0" />
						<xs:maxInclusive value="58156" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="media">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="fotografías" />
				<xs:element ref="vídeos" />
				<xs:element ref="podcasts" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="fotografías">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="fotografía" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="vídeos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="vídeo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="podcasts">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="podcast" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="hitos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="hito" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="puntos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="punto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="clasificaciones">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="3" ref="clasificación" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="nombre" type="xs:string" />
	<xs:element name="número" >
		<xs:simpleType>
				<xs:restriction base="xs:nonNegativeInteger">
					<xs:minInclusive value="1" />
					<xs:maxInclusive value="21" />
				</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="fecha" >
		<xs:simpleType>
				<xs:restriction base="xs:date">
					<xs:minInclusive value="2026-08-22" />
					<xs:maxInclusive value="2026-09-13" />
				</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="salida">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="longitud" use="required" >
						<xs:simpleType>
							<xs:restriction base="xs:float">
								<xs:minInclusive value="-6.87" />
								<xs:maxInclusive value="7.4" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="latitud" use="required" >
						<xs:simpleType>
							<xs:restriction base="xs:float">
								<xs:minInclusive value="36.42" />
								<xs:maxInclusive value="43.83" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="altitud" use="required" >
						<xs:simpleType>
							<xs:restriction base="xs:float">
								<xs:minInclusive value="0" />
								<xs:maxInclusive value="2408" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="meta">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="longitud" use="required" >
						<xs:simpleType>
							<xs:restriction base="xs:float">
								<xs:minInclusive value="-6.87" />
								<xs:maxInclusive value="7.4" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="latitud" use="required" >
						<xs:simpleType>
							<xs:restriction base="xs:float">
								<xs:minInclusive value="36.42" />
								<xs:maxInclusive value="43.83" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="altitud" use="required" >
						<xs:simpleType>
							<xs:restriction base="xs:float">
								<xs:minInclusive value="0" />
								<xs:maxInclusive value="2408" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="tipo">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Llana"/>
				<xs:enumeration value="Montaña"/>
				<xs:enumeration value="Contrarreloj individual"/>
				<xs:enumeration value="Contrarreloj por equipos"/>
				<xs:enumeration value="Media montaña"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="referencia" type="xs:string" />
	<xs:element name="fotografía" type="xs:string" />
	<xs:element name="vídeo" type="xs:string" />
	<xs:element name="podcast" type="xs:string" />

	<xs:element name="hito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="identificación" />
				<xs:element ref="tipoHito" />
			</xs:sequence>
			<xs:attribute name="longitud" use="required" >
				<xs:simpleType>
					<xs:restriction base="xs:float">
						<xs:minInclusive value="-6.87" />
						<xs:maxInclusive value="7.4" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="latitud" use="required" >
				<xs:simpleType>
					<xs:restriction base="xs:float">
						<xs:minInclusive value="36.42" />
						<xs:maxInclusive value="43.83" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="altitud" use="required" >
				<xs:simpleType>
					<xs:restriction base="xs:float">
						<xs:minInclusive value="0" />
						<xs:maxInclusive value="2408" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="distancia" use="required" >
				<xs:simpleType>
					<xs:restriction base="xs:float">
						<xs:minInclusive value="0" />
						<xs:maxInclusive value="210.8" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="bonificación" type="xs:boolean" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="punto">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="identificación" />
			</xs:sequence>
			<xs:attribute name="longitud" use="required" >
				<xs:simpleType>
					<xs:restriction base="xs:float">
						<xs:minInclusive value="-6.87" />
						<xs:maxInclusive value="7.4" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="latitud" use="required" >
				<xs:simpleType>
					<xs:restriction base="xs:float">
						<xs:minInclusive value="36.42" />
						<xs:maxInclusive value="43.83" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="altitud" use="required" >
				<xs:simpleType>
					<xs:restriction base="xs:float">
						<xs:minInclusive value="0" />
						<xs:maxInclusive value="2408" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="distancia" use="required" >
				<xs:simpleType>
					<xs:restriction base="xs:float">
						<xs:minInclusive value="0" />
						<xs:maxInclusive value="210.8" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name="identificación" type="xs:string" />
	<xs:element name="tipoHito">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="1ª categoría"/>
				<xs:enumeration value="2ª categoría"/>
				<xs:enumeration value="3ª categoría"/>
				<xs:enumeration value="Esprint intermedio"/>
				<xs:enumeration value="Esprint bonificado"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="clasificación">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="título" />
				<xs:element ref="primero" />
				<xs:element ref="segundo" />
				<xs:element ref="tercero" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="título" type="xs:string" />
	<xs:element name="primero" type="xs:string" />
	<xs:element name="segundo">
		<xs:complexType>
			<xs:simpleContent> 
				<xs:extension base="xs:string">
					<xs:attribute name="tiempo" use="required" >
						<xs:simpleType>
							<xs:restriction base="xs:duration">
								<xs:minInclusive value="PT0H0M0S" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="tercero">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="tiempo" use="required" >
						<xs:simpleType>
							<xs:restriction base="xs:duration">
								<xs:minInclusive value="PT0H0M0S" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== JimenaVazquez/sew/xml/etapaEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>

<etapas xmlns="http://www.uniovi.es" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.uniovi.es etapa.xsd">

<etapa longitud="104.8" tiempoGanador="PT2H40M35S" velocidadMediaGanador="39" desnivel="2890">
    <nombre>Andorra la Vella a Andorra la Vella</nombre>
    <número>4</número>
    <fecha>2026-08-25</fecha>

    <salida longitud="1.552684" latitud="42.513526" altitud="1150">Andorra la Vella</salida>
    <meta longitud="1.526117" latitud="42.505088" altitud="1011">Andorra la Vella (centro)</meta>
    <tipo>Montaña</tipo>

    <referencias>
        <referencia>"https://www.lavuelta.es/es/etapa-4"</referencia>
        <referencia>"https://www.olympics.com/es/noticias/vuelta-espana-2026-cuarta-etapa-25-agosto-recorrido-andorra-puertos-como-ver"</referencia>
        <referencia>"https://www.esciclismo.com/actualidad/carretera/92679.html"</referencia>
    </referencias>
    
    <media>

        <fotografías>
            <fotografía>carrera.png</fotografía>
            <fotografía>andorra.png</fotografía>
            <fotografía>ganador.png</fotografía>
        </fotografías>

        <vídeos>
            <vídeo>resumen.mp4</vídeo>
        </vídeos>

        <podcasts>
            <podcast>analisis.mp3</podcast>
        </podcasts>

    </media>
    
    <hitos>

        <hito longitud="1.719381" latitud="42.540176" altitud="2398" distancia="25.2" bonificación="false">
            <identificación>Port de Envalira</identificación>
            <tipoHito>1ª categoría</tipoHito>
        </hito>

        <hito longitud="1.547910" latitud="42.527751" altitud="1788" distancia="59.3" bonificación="false">
            <identificación>Collada de Beixalis</identificación>
            <tipoHito>1ª categoría</tipoHito>
        </hito>

        <hito longitud="1.532713" latitud="42.555576" altitud="1289" distancia="68.8" bonificación="false">
            <identificación>Ordino</identificación>
            <tipoHito>Esprint intermedio</tipoHito>
        </hito>

        <hito longitud="1.572304" latitud="42.556078" altitud="1971" distancia="78.7" bonificación="false">
            <identificación>Coll d'Ordino</identificación>
            <tipoHito>1ª categoría</tipoHito>
        </hito>

        <hito longitud="1.531641" latitud="42.500699" altitud="1342" distancia="100" bonificación="true">
            <identificación>Alto de la Comella</identificación>
            <tipoHito>3ª categoría</tipoHito>
        </hito>

    </hitos>

    <puntos>

        <punto longitud="1.566504" latitud="42.525979" altitud="1212" distancia="1.9">
            <identificación>1-A - 1</identificación>
        </punto>

        <punto longitud="1.583578" latitud="42.532106" altitud="1313" distancia="3.6">
            <identificación>1-B - 2</identificación>
        </punto>
 
        <punto longitud="1.591532" latitud="42.538074" altitud="1363" distancia="4.6">
            <identificación>1-C - 3</identificación>
        </punto>
 
        <punto longitud="1.591096" latitud="42.563844" altitud="1520" distancia="7.6">
            <identificación>1-D - 4</identificación>
        </punto>

        <punto longitud="1.594329" latitud="42.566109" altitud="1524" distancia="8.0">
            <identificación>1-E - 5</identificación>
        </punto>

        <punto longitud="1.605146" latitud="42.570374" altitud="1541" distancia="9.2">
            <identificación>1-F - 6</identificación>
        </punto>

        <punto longitud="1.648315" latitud="42.580023" altitud="1675" distancia="13.1">
            <identificación>1-G - 7</identificación>
        </punto>

        <punto longitud="1.664185" latitud="42.583861" altitud="1751" distancia="14.8">
            <identificación>1-H - 8</identificación>
        </punto>

        <punto longitud="1.664389" latitud="42.577422" altitud="1807" distancia="15.6">
            <identificación>1-I - 9</identificación>
        </punto>

        <punto longitud="1.696388" latitud="42.550918" altitud="2038" distancia="19.8">
            <identificación>1-J - 10</identificación>
        </punto>
 
        <punto longitud="1.705109" latitud="42.542204" altitud="2141" distancia="21.4">
            <identificación>C1-A - 11</identificación>
        </punto>

        <punto longitud="1.703902" latitud="42.549881" altitud="2208" distancia="22.3">
            <identificación>C1-B - 12</identificación>
        </punto>

        <punto longitud="1.711819" latitud="42.540644" altitud="2306" distancia="23.6">
            <identificación>C1-C - 13</identificación>
        </punto>

        <punto longitud="1.719262" latitud="42.537831" altitud="2374" distancia="25.7">
            <identificación>C1-D - 14</identificación>
        </punto>

        <punto longitud="1.727605" latitud="42.543507" altitud="2260" distancia="27.3">
            <identificación>C1-E - 15</identificación>
        </punto>

        <punto longitud="1.726642" latitud="42.537540" altitud="2216" distancia="28.0">
            <identificación>C1-F - 16</identificación>
        </punto>

        <punto longitud="1.732191" latitud="42.548836" altitud="2109" distancia="29.5">
            <identificación>C1-G - 17</identificación>
        </punto>

        <punto longitud="1.732325" latitud="42.544127" altitud="2095" distancia="30.0">
            <identificación>C1-H - 18</identificación>
        </punto>

        <punto longitud="1.735644" latitud="42.543407" altitud="2085" distancia="30.3">
            <identificación>C1-I - 19</identificación>
        </punto>

        <punto longitud="1.737797" latitud="42.548496" altitud="2052" distancia="30.9">
            <identificación>C1-J - 20</identificación>
        </punto>

        <punto longitud="1.731586" latitud="42.546105" altitud="2051" distancia="31.6">
            <identificación>2-A - 21</identificación>
        </punto>

        <punto longitud="1.702324" latitud="42.545674" altitud="2047" distancia="34.1">
            <identificación>2-B - 22</identificación>
        </punto>

        <punto longitud="1.674646" latitud="42.573395" altitud="1851" distancia="38.0">
            <identificación>2-C - 23</identificación>
        </punto>

        <punto longitud="1.666365" latitud="42.576994" altitud="1818" distancia="38.8">
            <identificación>2-D - 24</identificación>
        </punto>

        <punto longitud="1.664476" latitud="42.583705" altitud="1754" distancia="39.8">
            <identificación>2-E - 25</identificación>
        </punto>

        <punto longitud="1.652999" latitud="42.578039" altitud="1701" distancia="41.1">
            <identificación>2-F - 26</identificación>
        </punto>

        <punto longitud="1.601239" latitud="42.567333" altitud="1528" distancia="46.0">
            <identificación>2-K - 99</identificación>
        </punto>

        <punto longitud="1.588731" latitud="42.553085" altitud="1407" distancia="48.2">
            <identificación>2-G - 27</identificación>
        </punto>

        <punto longitud="1.591498" latitud="42.538151" altitud="1358" distancia="50.0">
            <identificación>2-H - 28</identificación>
        </punto>

        <punto longitud="1.579955" latitud="42.531802" altitud="1292" distancia="51.3">
            <identificación>2-I - 29</identificación>
        </punto>

        <punto longitud="1.570873" latitud="42.529748" altitud="1233" distancia="52.2">
            <identificación>2-J - 30</identificación>
        </punto>

        <punto longitud="1.571949" latitud="42.534090" altitud="1247" distancia="52.9">
            <identificación>C2-A - 31</identificación>
        </punto>

        <punto longitud="1.567226" latitud="42.531458" altitud="1303" distancia="53.7">
            <identificación>C2-B - 32</identificación>
        </punto>

        <punto longitud="1.561607" latitud="42.533327" altitud="1432" distancia="54.6">
            <identificación>C2-C - 33</identificación>
        </punto>

        <punto longitud="1.558434" latitud="42.530141" altitud="1553" distancia="55.9">
            <identificación>C2-D - 34</identificación>
        </punto>

        <punto longitud="1.554903" latitud="42.532950" altitud="1654" distancia="57.4">
            <identificación>C2-E - 35</identificación>
        </punto>

        <punto longitud="1.554903" latitud="42.532950" altitud="1654" distancia="57.4">
            <identificación>C2-F - 36</identificación>
        </punto>

        <punto longitud="1.551967" latitud="42.527395" altitud="1704" distancia="58.2">
            <identificación>C2-G - 37</identificación>
        </punto>

        <punto longitud="1.550290" latitud="42.530575" altitud="1751" distancia="58.7">
            <identificación>C2-H - 38</identificación>
        </punto>

        <punto longitud="1.545896" latitud="42.529027" altitud="1772" distancia="59.5">
            <identificación>C2-I - 39</identificación>
        </punto>

        <punto longitud="1.549148" latitud="42.537919" altitud="1734" distancia="60.7">
            <identificación>C2-J - 40</identificación>
        </punto>

        <punto longitud="1.542759" latitud="42.536069" altitud="1675" distancia="61.3">
            <identificación>C2-K - 41</identificación>
        </punto>

        <punto longitud="1.541363" latitud="42.532491" altitud="1658" distancia="61.7">
            <identificación>C2-L - 42</identificación>
        </punto>

        <punto longitud="1.542380" latitud="42.538382" altitud="1593" distancia="62.5">
            <identificación>C2-M - 43</identificación>
        </punto>

        <punto longitud="1.530118" latitud="42.533940" altitud="1451" distancia="64.1">
            <identificación>C2-N - 44</identificación>
